#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker tag nandiheath/station-web nandiheath/station-web:$TRAVIS_COMMIT
docker push nandiheath/station-web:$TRAVIS_COMMIT