BEGIN WORK;

CREATE TABLE IF NOT EXISTS "EMBED"(
	"IDENTIFIER" SERIAL NOT NULL,
	"LESSON" INTEGER NOT NULL,
	"NUMBER" SMALLINT NOT NULL,
	"TITLE" TEXT NOT NULL,
	"KIND" SMALLINT NOT NULL,
	"VALUE" BYTEA NOT NULL,
	PRIMARY KEY("IDENTIFIER"),
	FOREIGN KEY("LESSON")
		REFERENCES "LESSON"("IDENTIFIER")
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

END WORK;
