WITH "S" AS (SELECT "IDENTIFIER", ROW_NUMBER() OVER(ORDER BY "IDENTIFIER") AS "N" FROM "SUBJECT")
	UPDATE "SUBJECT"
		SET "IDENTIFIER"="S"."N"
		FROM "S"
		WHERE "SUBJECT"."IDENTIFIER"="S"."IDENTIFIER";
SELECT SETVAL('"SUBJECT_IDENTIFIER_seq"', (SELECT MAX("IDENTIFIER") FROM "SUBJECT"), true);

WITH "S" AS (SELECT "IDENTIFIER", ROW_NUMBER() OVER(ORDER BY "IDENTIFIER") AS "N" FROM "COURSE")
	UPDATE "COURSE"
		SET "IDENTIFIER"="S"."N"
		FROM "S"
		WHERE "COURSE"."IDENTIFIER"="S"."IDENTIFIER";
SELECT SETVAL('"COURSE_IDENTIFIER_seq"', (SELECT MAX("IDENTIFIER") FROM "COURSE"), true);

WITH "S" AS (SELECT "IDENTIFIER", ROW_NUMBER() OVER(ORDER BY "IDENTIFIER") AS "N" FROM "LESSON")
	UPDATE "LESSON"
		SET "IDENTIFIER"="S"."N"
		FROM "S"
		WHERE "LESSON"."IDENTIFIER"="S"."IDENTIFIER";
SELECT SETVAL('"LESSON_IDENTIFIER_seq"', (SELECT MAX("IDENTIFIER") FROM "LESSON"), true);

WITH "S" AS (SELECT "IDENTIFIER", ROW_NUMBER() OVER(ORDER BY "IDENTIFIER") AS "N" FROM "EMBED")
	UPDATE "EMBED"
		SET "IDENTIFIER"="S"."N"
		FROM "S"
		WHERE "EMBED"."IDENTIFIER"="S"."IDENTIFIER";
SELECT SETVAL('"EMBED_IDENTIFIER_seq"', (SELECT MAX("IDENTIFIER") FROM "EMBED"), true);

WITH "S" AS (SELECT "IDENTIFIER", ROW_NUMBER() OVER(ORDER BY "IDENTIFIER") AS "N" FROM "QUESTION")
	UPDATE "QUESTION"
		SET "IDENTIFIER"="S"."N"
		FROM "S"
		WHERE "QUESTION"."IDENTIFIER"="S"."IDENTIFIER";
SELECT SETVAL('"QUESTION_IDENTIFIER_seq"', (SELECT MAX("IDENTIFIER") FROM "QUESTION"), true);

WITH "S" AS (SELECT "IDENTIFIER", ROW_NUMBER() OVER(ORDER BY "IDENTIFIER") AS "N" FROM "ANSWER")
	UPDATE "ANSWER"
		SET "IDENTIFIER"="S"."N"
		FROM "S"
		WHERE "ANSWER"."IDENTIFIER"="S"."IDENTIFIER";
SELECT SETVAL('"ANSWER_IDENTIFIER_seq"', (SELECT MAX("IDENTIFIER") FROM "ANSWER"), true);

VACUUM;
