CREATE TABLE "USER"(
	"NAME" TEXT NOT NULL,
	"PASSWORD" TEXT NOT NULL,
	"ROLE" SMALLINT NOT NULL,
	PRIMARY KEY("NAME")
);

CREATE SEQUENCE "SUBJECT_IDENTIFIER_seq" AS INTEGER;
CREATE TABLE "SUBJECT"(
	"IDENTIFIER" INTEGER NOT NULL DEFAULT nextval('"SUBJECT_IDENTIFIER_seq"'),
	"TITLE" TEXT NOT NULL,
	"DESCRIPTION" TEXT NOT NULL,
	PRIMARY KEY("IDENTIFIER")
);
ALTER SEQUENCE "SUBJECT_IDENTIFIER_seq" OWNED BY "SUBJECT"."IDENTIFIER";

CREATE SEQUENCE "COURSE_IDENTIFIER_seq" AS INTEGER;
CREATE TABLE "COURSE"(
	-- "IDENTIFIER" SERIAL NOT NULL,
	"IDENTIFIER" INTEGER NOT NULL DEFAULT nextval('"COURSE_IDENTIFIER_seq"'::regclass),
	"SUBJECT" INTEGER NOT NULL,
	"TITLE" TEXT NOT NULL,
	"DESCRIPTION" TEXT NOT NULL,
	PRIMARY KEY("IDENTIFIER"),
	FOREIGN KEY("SUBJECT") REFERENCES "SUBJECT"("IDENTIFIER")
		ON DELETE CASCADE
		ON UPDATE CASCADE
);
ALTER SEQUENCE "COURSE_IDENTIFIER_seq" OWNED BY "COURSE"."IDENTIFIER";

CREATE SEQUENCE "LESSON_IDENTIFIER_seq" AS INTEGER;
CREATE TABLE "LESSON"(
	-- "IDENTIFIER" SERIAL NOT NULL,
	"IDENTIFIER" INTEGER NOT NULL DEFAULT nextval('"LESSON_IDENTIFIER_seq"'::regclass),
	"COURSE" INTEGER NOT NULL,
	"NUMBER" INTEGER NOT NULL,
	"TITLE" TEXT NOT NULL,
	"CONTENT" TEXT NOT NULL,
	PRIMARY KEY("IDENTIFIER"),
	FOREIGN KEY("COURSE") REFERENCES "COURSE"("IDENTIFIER")
		ON DELETE CASCADE
		ON UPDATE CASCADE
);
ALTER SEQUENCE "LESSON_IDENTIFIER_seq" OWNED BY "LESSON"."IDENTIFIER";

CREATE SEQUENCE "QUESTION_IDENTIFIER_seq" AS INTEGER;
CREATE TABLE "QUESTION"(
	-- "IDENTIFIER" SERIAL NOT NULL,
	"IDENTIFIER" INTEGER NOT NULL DEFAULT nextval('"QUESTION_IDENTIFIER_seq"'::regclass),
	"LESSON" INTEGER NOT NULL,
	"TEXT" TEXT NOT NULL,
	PRIMARY KEY("IDENTIFIER"),
	FOREIGN KEY("LESSON") REFERENCES "LESSON"("IDENTIFIER")
		ON DELETE CASCADE
		ON UPDATE CASCADE
);
ALTER SEQUENCE "QUESTION_IDENTIFIER_seq" OWNED BY "QUESTION"."IDENTIFIER";

CREATE SEQUENCE "ANSWER_IDENTIFIER_seq" AS INTEGER;
CREATE TABLE "ANSWER"(
	-- "IDENTIFIER" SERIAL NOT NULL,
	"IDENTIFIER" INTEGER NOT NULL DEFAULT nextval('"ANSWER_IDENTIFIER_seq"'::regclass),
	"QUESTION" INTEGER NOT NULL,
	"TEXT" TEXT NOT NULL,
	PRIMARY KEY("IDENTIFIER"),
	FOREIGN KEY("QUESTION") REFERENCES "QUESTION"("IDENTIFIER")
		ON DELETE CASCADE
		ON UPDATE CASCADE
);
ALTER SEQUENCE "ANSWER_IDENTIFIER_seq" OWNED BY "ANSWER"."IDENTIFIER";
